apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-frontend
  template:
    metadata:
      labels:
        app: hello-frontend
    spec:
      containers:
      - name: hello-frontend
        image: hello-frontend:latest
        imagePullPolicy: Never  # Because we're using a local build
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-frontend-service
spec:
  type: NodePort
  selector:
    app: hello-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30090
