pipeline {
    agent any

    environment {
        IMAGE_NAME = "hello-frontend"
        K8S_YAML = "k8s/deployment.yaml"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[url: 'https://github.com/xinwuqingdao/BootstrapMicroservicePrototype.git']]
                ])
            }
        }

        stage('Install & Build Angular') {
            steps {
              
                dir('hello-frontend'){
                    sh '''
                      export NVM_DIR="$HOME/.nvm"
                      [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
                      nvm use 22
                      npm install
                      npm run build -- --configuration production
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('hello-frontend'){
                
                    sh 'docker build -t $IMAGE_NAME .'
                    
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                dir('hello-frontend'){
                    sh 'kubectl apply -f $K8S_YAML'
                }
            }
        }
    }
}
