pipeline {
    agent any

    environment {
        IMAGE_NAME = "hello-springboot"
    }

    stages {
        stage('Checkout') {
             steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[url: 'https://github.com/xinwuqingdao/BootstrapMicroservicePrototype.git']]
                ])
            }
        }

        stage('Build') {
            steps {
				 dir('demo') {
                    echo 'Building the project...'
                    sh './mvnw clean package'
                }
            }
        }

        stage('Docker Build') {
            steps {
				dir('demo'){
					echo 'Building Docker image...'
                	sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('K8s Deploy') {
            steps {
				dir('demo'){
					echo 'Deploy container image to kubernetes...'
                	sh 'kubectl apply -f k8s/deployment.yaml'
                }
            }
        }
    }
}
