pipeline {
    agent any

    environment {
        IMAGE_NAME = "hello-springboot"
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/xinwuqingdao/BootstrapMicroservicePrototype.git'
            }
        }

        stage('Build') {
            steps {
                sh './mvnw clean package'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('K8s Deploy') {
            steps {
                sh 'kubectl apply -f k8s/deployment.yaml'
            }
        }
    }
}
